[package]
name = "vhost"
version = "0.1.0"
authors = ["Liu Jiang <gerry@linux.alibaba.com>"]
repository = "https://github.com/rust-vmm/vhost"
license = "Apache-2.0 or BSD-3-Clause"

[features]
default = []
vhost-vsock = []
vhost-kern = ["vm-memory/backend-mmap"]
vhost-user-master = []
vhost-user-slave = []

[dependencies]
bitflags = ">=1.0.1"
libc = ">=0.2.39"

vmm-sys-util = { git = "https://github.com/rust-vmm/vmm-sys-util.git", branch = "master" }
#vm-memory = { git = "https://github.com/rust-vmm/vm-memory.git", branch = "master", optional = true }
vm-memory = { git = "https://github.com/jiangliu/vm-memory.git", branch = "host_address", optional = true }
